#%RAML 1.0 Trait
headers:
  transactionId:
    type: string
    required: true
    example: hdsfhjdh-jxbv859-sjdf7643-3746bbd
queryParameters:
  companyName:
    type: string
    required: false
    example: TravelOnTip
  departureLocation:
    type: string
    required: false
    example: Beauna Vista Singapore
  destinationLocation:
    type: string
    required: false
    example: Klang Malaysia